### PR TITLE
fix: remove stupid garbage

### PR DESCRIPTION
**Pull request by DataM0del**

### CODE REVIEW

**Comment by kkkfasya** [comment]
NO THIS IS NECESSARY, THIS IS THE LORE OF THE OG COOMER YOU DO NOT MESS WITH THIS

**Comment by DataM0del** [comment]
> NO THIS IS NECESSARY, THIS IS THE LORE OF THE OG COOMER YOU DO NOT MESS WITH THIS

the "lore" is probably stolen from a cornhub video

**Comment by DataM0del** [comment]
and cornhub video lore is not needed in a Wayland zoomer application

**Comment by kkkfasya** [comment]
> and cornhub video lore is not needed in a Wayland zoomer application

Wrong :angry: , this is coomer, special wayland zoomer for gooner

**Comment by DataM0del** [comment]
> > and cornhub video lore is not needed in a Wayland zoomer application
> 
> Wrong 😠 , this is coomer, special wayland zoomer for gooner

well I don't goon and I'd use coomer if it actually worked lol.

**Comment by kkkfasya** [comment]
> well I don't goon and I'd use coomer if it actually worked lol.

sounds like skill issue

**Pull request closed without merging**
